### ISSUE TITLE
No persistent storage: Email being delete after container is stopped 

### ISSUE THREAD

**Issue by AndreSouzaAbreu** [lejmr/iredmail-docker#84]
I'm running this iredmail  container using docker-compose, and  all emails and accounts are deleted every time the container restarts.

So, if I run:

```
docker-compose up -d
```

It works, and I can create accounts and send emails. But after running:

```
docker-compose down
```

and then restarting the container with `docker-compose up -d`, all mails and accounts get deleted.

**Steps to reproduce:**

**1: create network**

```
docker network create webproxy
```

**2: set up nginx proxy**

Set a up a nginx proxy such as [this one](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion)

**3: Start**

Just copy the configuration below 
Here is `docker-composer.yml`

```
version: '3.5'
services:
  iredmail:
    image: lejmr/iredmail:mysql-latest
    container_name: iredmail
    restart: unless-stopped
    hostname: ${DOMAIN}
    privileged: yes
    ports:
      - "25:25"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    volumes:
      - ${PATH_MYSQL}/var/lib/mysql
      - ${PATH_VMAIL}/var/vmail
      - ${PATH_CLAMAV}:/var/lib/clamav
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - POSTMASTER_PASSWORD={PLAIN}${POSTMASTER_PASSWORD}
      - IREDAPD_PLUGINS="['reject_null_sender', 'reject_sender_login_mismatch', 'greylisting', 'throttle', 'amavisd_wblist', 'sql_alias_access_policy']"
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - VIRTUAL_PROTO=${VIRTUAL_PROTO}
      - SSL_POLICY=Mozilla-Modern
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

networks:
   default:
     external:
       name: ${NETWORK}
```

An example of how the `.env` looks like:

```
MYSQL_ROOT_PASSWORD=astrongpasswordformysql
POSTMASTER_PASSWORD=astrongpasswordforpostmaster
DOMAIN=mydomain.com
VIRTUAL_PORT=443
VIRTUAL_PROTO=https
LETSENCRYPT_EMAIL=myemail@gmail.com
NETWORK=webproxy
PATH_MYSQL=/var/www/mail/mysql
PATH_CLAMAV=/var/www/mail/clamav
PATH_VMAIL=/var/www/mail/vmail
```

And that is it.

----------------

So this problem is quite bad. Even though configuration above is mapping the volumes from host to the container, the emails and accounts are being deleted every time.

Help me please..
